version: "2.4"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pern_postgres
    environment:
      POSTGRES_DB: finguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend-node/migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
      - ./backend-node/migrations/kyc/001_create_kyc_tables.sql:/docker-entrypoint-initdb.d/002_kyc.sql

  backend-node:
    build:
      context: ./backend-node
      target: dev
    container_name: pern_backend_node
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/finguard
      JWT_ACCESS_SECRET: dev_access_secret_change_me
      JWT_REFRESH_SECRET: dev_refresh_secret_change_me
      JWT_ACCESS_TTL: 15m
      JWT_REFRESH_TTL: 7d
      CORS_ORIGIN: http://localhost:5173,http://localhost:5176
      FASTAPI_URL: http://backend-fastapi:8080
    ports:
      - "4000:4000"
    volumes:
      - ./backend-node:/app
      - /app/node_modules

  backend-fastapi:
    build:
      context: ./backend-fastapi
    container_name: pern_backend_fastapi
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:admin@postgres:5432/finguard
    ports:
      - "8080:8080"
    volumes:
      - ./backend-fastapi:/app

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: pern_frontend
    depends_on:
      - backend-node
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api/v1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
